[window]
opacity = 0.75
padding.x = 10
padding.y = 10

[font]
normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"
size = 10

[mouse]
hide_when_typing = true

[cursor]
style.shape="Block"
style.blinking="On"
