[window]
opacity = 0.75
padding.x = 30
padding.y = 200

[font]
normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"
size=60

[mouse]
hide_when_typing = true

[cursor]
style.shape="Block"
style.blinking="On"
