#!/bin/bash

# Define dotfile repository location
dotfiles_dir="$HOME/dotfiles"

echo "Beginning setup script..."

# List of configuration files
CONFIG_FILES=(
    ".config/alacritty/alacritty.toml"
    ".config/i3/config"
    ".config/nvim/init.vim"
    ".config/polybar/config.ini"
    ".config/polybar/launch.sh"
    ".config/kitty/kitty.conf"
    ".config/bat/config"
    ".config/rofi/config.rasi"
)

# Function for copying configs
create_symlink() {
    local src=$1
    local dest=$2

    # check if destination exists
    if [ -f "$dest" ]; then
        echo "Backing up existing $dest to ${dest}.bak"
        sudo mv "$dest" "${dest}.bak"
    fi

    # create the symlink
    sudo ln -s "$src" "$dest"
}

# Loop for copying configs
for file in "${CONFIG_FILES[@]}"; do
    src="$dotfiles_dir/$file"
    dest="$HOME/$file"

    if [ -f "$src" ]; then
        create_symlink "$src" "$dest"
    else
        echo "Warning: $src does not exist, skipping."
    fi

done

NIXOS_DIR="/etc/nixos"
MY_NIXOS_DIR=".config/nixos/"
NIXOS_CONF_FILES=(
    "configuration.nix"
    "hardware-configuration.nix"
)
# Add links to nixos configs
if [ -d "$NIXOS_DIR" ]; then
    for file in "${NIXOS_CONF_FILES[@]}"; do
        src="$dotfiles_dir/$MY_NIXOS_DIR/$file"
        dest="$NIXOS_DIR/$file"
        if [ -f "$src" ]; then
            create_symlink "$src" "$dest"
        else
            echo "Warning: $src does not exist, skipping."
        fi
    done
fi
unset MY_NIXOS_DIR
unset NIXOS_DIR
unset NIXOS_CONF_FILES

echo "Cleaning up..."
unset src
unset dest
unset file
unset dofiles_dir

echo "Completed setup script..."
