#!/bin/bash

# Define dotfile repository location
dotfiles_dir="$HOME/dotfiles"

echo "Beginning setup script..."

# List of configuration files
CONFIG_FILES=(
    ".config/alacritty/alacritty.toml"
    ".config/i3/config"
    ".config/nvim/init.vim"
    ".config/polybar/config.ini"
)

# Function for copying configs
create_symlink() {
    local src=$1
    local dest=$2

    # check if destination exists
    if [ -f "$dest" ]; then
        echo "Backing up existing $dest to ${dest}.bak"
        mv "$dest" "${dest}.bak"
    fi

    # create the symlink
    ln -s "$src" "$dest"
}

# Loop for copying configs
for file in "${CONFIG_FILES[@]}"; do
    src="$dotfiles_dir/$file"
    dest="$HOME/$file"

    if [ -f "$src" ]; then
        create_symlink "$src" "$dest"
    else
        echo "Warning: $src does not exist, skipping."
    fi

done

SYSTEM_NIXOS_CONFIG_DIR="/etc/nixos"
# Add links to nixos configs
create_symlink "$dotfiles_dir/.config/nixos/configuration.nix" "$SYSTEM_NIXOS_CONFIG_DIR/configuration.nix"
create_symlink "$dotfiles_dir/.config/nixos/hardware-configuration.nix" "$SYSTEM_NIXOS_CONFIG_DIR/hardware-configuration.nix"

echo "Cleaning up..."
unset src
unset dest
unset file
unset dofiles_dir
unset MY_NIXOS_SUBDIR
unset SYSTEM_NIXOS_CONFIG_DIR

echo "Completed setup script..."
