[window]
opacity = 0.50
padding.x = 10
padding.y = 10

[font]
normal.family = "Consolas"
bold.family = "Consolas"
italic.family = "Consolas"
bold_italic.family = "Consolas"

[mouse]
hide_when_typing = true

[cursor]
style.shape="Block"
style.blinking="On"
